- name: 'Create access to new users in the organization Musa'
  hosts: localhost
  vars_files:
    - vaults.yaml
  tasks:
    - name: Create User to WMS - AWS Cognito
      command: >
        aws cognito-idp admin-create-user
        --user-pool-id "{{ user_pool_id }}"
        --username "{{ phone }}"
        --desired-delivery-mediums SMS
        --message-action SUPPRESS
        --temporary-password "{{ password }}"
        --user-attributes Name=email,Value="{{ email }}" Name=phone_number,Value="{{ phone }}" Name=email_verified,Value=true Name=phone_number_verified,Value=true
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
        AWS_DEFAULT_REGION: "us-east-1"
      become: no

    - name: Add user in group admin to access WMS - AWS Cognito
      command: >
        aws cognito-idp admin-add-user-to-group
        --user-pool-id "{{ user_pool_id }}"
        --username "{{ phone }}"
        --group-name "{{ group_name }}"
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
        AWS_DEFAULT_REGION: "us-east-1"
      become: no